version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "LoRa-Monitor"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-uridd08khucn"
s3_prefix = "LoRa-Monitor"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
