AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LoRa-Monitor

  Sample SAM Template for LoRa-Monitor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  TTNWebhookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: build/
      Handler: bootstrap.is.the.handler
      Runtime: provided.al2
      Architectures:
        - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        HTTPRequests:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
          HTTPRequestRoots:
            Type: Api
            Properties:
              Path: /
              Method: ANY
  DynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: TemperatureReadings
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      ProvisionedThroughput:
        WriteCapacityUnits: 5
        ReadCapacityUnits: 5
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - KeyType: HASH
          AttributeName: id


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  TTNWebhookApi:
    Description: "API Gateway endpoint URL for Prod stage for TTN webhook function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/webhook/"
  TTNWebhookFunction:
    Description: "TTN webhook Lambda Function ARN"
    Value: !GetAtt TTNWebhookFunction.Arn
  TTNWebhookFunctionIamRole:
    Description: "Implicit IAM Role created for TTN webhook function"
    Value: !GetAtt TTNWebhookFunction.Arn
