version: 2.1

jobs:
  test:
    docker:
      - image: cimg/rust:1.88.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.toml" }}
      - run: cargo --version
      - run:
          name: Run Tests
          command: "cargo test"
      - save_cache:
          key: cargo-v1-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo
  build:
    docker:
      - image: cimg/rust:1.88.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-v1-{{ checksum "Cargo.toml" }}
      - run:
          name: Install Rust deps
          command: make ci-install-deps
      - run:
          name: Build
          command: "make build"
      - persist_to_workspace:
          root: build
          paths:
            - bootstrap
      - save_cache:
          key: cargo-v1-{{ checksum "Cargo.toml" }}
          paths:
            - ~/.cargo

  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - attach_workspace:
          at: build
      - restore_cache:
          keys:
            - uv-v1-{{ checksum "pyproject.toml" }}
      - run:
          name: Install uv
          command: pip install uv
      - run:
          name: Install dependencies
          command: uv sync --no-group dev
      - run:
          name: Deploy
          command: uv run sam deploy
      - save_cache:
          when: on_success
          paths:
            - ~/.cache/uv
          key: uv-v1-{{ checksum "pyproject.toml" }}


workflows:
  version: 2
  test_build_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build
          context: [ stroud-weather-monitor ]
